//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogoSoftWebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dboEntities : DbContext
    {
        public dboEntities()
            : base("name=dboEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cat_Productos> Cat_Productos { get; set; }
        public virtual DbSet<Ope_Facturas> Ope_Facturas { get; set; }
        public virtual DbSet<Ope_Facturas_Detalles> Ope_Facturas_Detalles { get; set; }
    
        public virtual ObjectResult<spConsultaVentas_Result> spConsultaVentas(string noDocumentoInicial, string noDocumentoFinal, string nombreCliente)
        {
            var noDocumentoInicialParameter = noDocumentoInicial != null ?
                new ObjectParameter("NoDocumentoInicial", noDocumentoInicial) :
                new ObjectParameter("NoDocumentoInicial", typeof(string));
    
            var noDocumentoFinalParameter = noDocumentoFinal != null ?
                new ObjectParameter("NoDocumentoFinal", noDocumentoFinal) :
                new ObjectParameter("NoDocumentoFinal", typeof(string));
    
            var nombreClienteParameter = nombreCliente != null ?
                new ObjectParameter("NombreCliente", nombreCliente) :
                new ObjectParameter("NombreCliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultaVentas_Result>("spConsultaVentas", noDocumentoInicialParameter, noDocumentoFinalParameter, nombreClienteParameter);
        }
    }
}
