//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogoSoftWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ope_Facturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ope_Facturas()
        {
            this.Ope_Facturas_Detalles = new HashSet<Ope_Facturas_Detalles>();
        }
    
        public long No_Factura { get; set; }
        public string Numero_Comprobante { get; set; }
        public string Nombre_Cliente { get; set; }
        public string Cedula { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Descuento { get; set; }
        public decimal Total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ope_Facturas_Detalles> Ope_Facturas_Detalles { get; set; }
    }
}
