//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogoSoftWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ope_Facturas_Detalles
    {
        public long No_Factura_Detalle { get; set; }
        public long No_Factura { get; set; }
        public int Producto_ID { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio { get; set; }
        public decimal Importe { get; set; }
    
        public virtual Cat_Productos Cat_Productos { get; set; }
        public virtual Ope_Facturas Ope_Facturas { get; set; }
    }
}
